#!/usr/bin/env bash
# Bash script to Install and configure HAproxy on your lb-01 server.
sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo chown -R ubuntu /etc/haproxy
sudo echo "
frontend web-frontend
        bind *:80
        mode http
        default_backend web-backend
backend web-backend
        balance roundrobin
        server 249924-lb-01	ubuntu@54.237.217.250:80 check
        server 249924-lb-01	ubuntu@54.237.217.250:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
